Allow immediate switching when top quality index changes
bbc/dash.js pull request #52
Opened 2016-11-15 10:18 UTC by JontyUsborne

When the max representation available to ABR changes because of updateQuality or Portal Bitrate change, the Buffer Level rule prevents switching because the buffer is larger than the stable bitrate buffer target (12 or 20s). The previous "top quality" target buffer size of (60s) means that any appending to the buffer is suppressed for 48s so the user sees their buffer collapse.

Any change in getTopQualityIndexFor() now allows an immediate update of the rules. This should prevent the buffer near exhausting when quality changes and therefore reduce risk, especially as this happens whenever a user goes fullscreen.

Expensive bufferLevelRule is also not called now if getNextFragment is already triggered by isReplacement or topQualityChanged.

2016-11-21 11:00 UTC, robertbryer requested changes

2016-11-21 11:00 UTC, robertbryer commented on src/streaming/controllers/ScheduleController.js
> +        if ( (isReplacement = replaceRequestArray.length > 0) ||
Don't do assignment inside the condition of an if statement. I'd prefer the old way with the const above, or just use the rhs of the assignment alone (topQualityChanged and readyToLoad not being used after the if)

2017-01-11 16:53 UTC, JontyUsborne commented
This was merged into development (#1667). Did it make it through via 2.4 integration @robertbryer? Can close this if so obviously.

2017-01-11 17:26 UTC, robertbryer commented
This did come through 2.4 rather than through this pr

2017-01-11 17:26 UTC, closed without merging